#############################################################################
# Makefile for building: Judgement1
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  ../Judge_sh006/Judgement1.pro
# Template: app
# Command: /home/ruanxinyao/lastyear_project/QT5.10/5.10.1/gcc_64/bin/qmake -o Makefile ../Judge_sh006/Judgement1.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../Judge_sh006 -I. -I../QT5.10/5.10.1/gcc_64/include -I../QT5.10/5.10.1/gcc_64/include/QtWidgets -I../QT5.10/5.10.1/gcc_64/include/QtGui -I../QT5.10/5.10.1/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I../QT5.10/5.10.1/gcc_64/mkspecs/linux-g++
QMAKE         = /home/ruanxinyao/lastyear_project/QT5.10/5.10.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/ruanxinyao/lastyear_project/QT5.10/5.10.1/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/ruanxinyao/lastyear_project/QT5.10/5.10.1/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Judgement11.0.0
DISTDIR = /home/ruanxinyao/lastyear_project/Judgement1/.tmp/Judgement11.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/ruanxinyao/lastyear_project/QT5.10/5.10.1/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/ruanxinyao/lastyear_project/QT5.10/5.10.1/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Judge_sh006/main.cpp 
OBJECTS       = main.o
DIST          = ../QT5.10/5.10.1/gcc_64/mkspecs/features/spec_pre.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/unix.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/linux.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/sanitize.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/gcc-base.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/g++-base.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/g++-unix.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/qconfig.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/qt_functions.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/qt_config.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/spec_post.prf \
		../Judge_sh006/.qmake.stash \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/toolchain.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/default_pre.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/resolve_config.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/default_post.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/qml_debug.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/warn_on.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/qt.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/resources.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/moc.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/uic.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/unix/thread.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/qmake_use.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/file_copies.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/exceptions.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/yacc.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/lex.prf \
		../Judge_sh006/Judgement1.pro ../Judge_sh006/defthreshold.h \
		../Judge_sh006/distance.h \
		../Judge_sh006/getline.h \
		../Judge_sh006/mybox.h \
		../Judge_sh006/missingbox.h ../Judge_sh006/main.cpp
QMAKE_TARGET  = Judgement1
DESTDIR       = 
TARGET        = Judgement1


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Judge_sh006/Judgement1.pro ../QT5.10/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf ../QT5.10/5.10.1/gcc_64/mkspecs/features/spec_pre.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/unix.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/linux.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/sanitize.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/gcc-base.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/g++-base.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/common/g++-unix.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/qconfig.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/qt_functions.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/qt_config.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/toolchain.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/default_pre.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/resolve_config.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/default_post.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/qml_debug.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/warn_on.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/qt.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/resources.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/moc.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/uic.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/unix/thread.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/qmake_use.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/file_copies.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/exceptions.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/yacc.prf \
		../QT5.10/5.10.1/gcc_64/mkspecs/features/lex.prf \
		../Judge_sh006/Judgement1.pro \
		../QT5.10/5.10.1/gcc_64/lib/libQt5Widgets.prl \
		../QT5.10/5.10.1/gcc_64/lib/libQt5Gui.prl \
		../QT5.10/5.10.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile ../Judge_sh006/Judgement1.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../QT5.10/5.10.1/gcc_64/mkspecs/features/spec_pre.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/common/unix.conf:
../QT5.10/5.10.1/gcc_64/mkspecs/common/linux.conf:
../QT5.10/5.10.1/gcc_64/mkspecs/common/sanitize.conf:
../QT5.10/5.10.1/gcc_64/mkspecs/common/gcc-base.conf:
../QT5.10/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../QT5.10/5.10.1/gcc_64/mkspecs/common/g++-base.conf:
../QT5.10/5.10.1/gcc_64/mkspecs/common/g++-unix.conf:
../QT5.10/5.10.1/gcc_64/mkspecs/qconfig.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../QT5.10/5.10.1/gcc_64/mkspecs/features/qt_functions.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/qt_config.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../QT5.10/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/toolchain.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/default_pre.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/resolve_config.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/default_post.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/qml_debug.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/warn_on.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/qt.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/resources.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/moc.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/unix/opengl.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/uic.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/unix/thread.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/qmake_use.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/file_copies.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/exceptions.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/yacc.prf:
../QT5.10/5.10.1/gcc_64/mkspecs/features/lex.prf:
../Judge_sh006/Judgement1.pro:
../QT5.10/5.10.1/gcc_64/lib/libQt5Widgets.prl:
../QT5.10/5.10.1/gcc_64/lib/libQt5Gui.prl:
../QT5.10/5.10.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../Judge_sh006/Judgement1.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../QT5.10/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Judge_sh006/defthreshold.h ../Judge_sh006/distance.h ../Judge_sh006/getline.h ../Judge_sh006/mybox.h ../Judge_sh006/missingbox.h $(DISTDIR)/
	$(COPY_FILE) --parents ../Judge_sh006/main.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Judge_sh006/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../QT5.10/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../QT5.10/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../Judge_sh006/mainwindow.ui \
		../QT5.10/5.10.1/gcc_64/bin/uic
	/home/ruanxinyao/lastyear_project/QT5.10/5.10.1/gcc_64/bin/uic ../Judge_sh006/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_uic_clean 

####### Compile

main.o: ../Judge_sh006/main.cpp ../Judge_sh006/mybox.h \
		../Judge_sh006/getline.h \
		../Judge_sh006/missingbox.h \
		../Judge_sh006/defthreshold.h \
		../Judge_sh006/distance.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Judge_sh006/main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

